### ISSUE TITLE
doesnt work lot of url

### ISSUE THREAD

**Issue by simplysexyboy** [dfirsec/blacklist_check#12]
Traceback (most recent call last):
  File "/root/blacklist_check/utils/main_worker.py", line 199, in fetch
    resp.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/httpx/_models.py", line 1510, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '503 Service Temporarily Unavailable' for url 'https://www.threatcrowd.org/feeds/ips.txt'
For more information check: https://httpstatuses.com/503

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "blacklist_check.py", line 239, in <module>
    main()
  File "blacklist_check.py", line 104, in main
    pbl.update_list()
  File "/root/blacklist_check/utils/main_worker.py", line 256, in update_list
    bl_dict["Blacklists"][name] = self.get_feeds(url)
  File "/root/blacklist_check/utils/main_worker.py", line 212, in get_feeds
    results = trio.run(self.fetch, feed)
  File "/usr/local/lib/python3.6/site-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/root/blacklist_check/utils/main_worker.py", line 205, in fetch
    print(f"    {Tc.error}{Tc.dl_error} {Tc.gray}{url}{Tc.rst}")
  File "/usr/local/lib/python3.6/site-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.6/site-packages/colorama/ansitowin32.py", line 172, in write
    self.wrapped.write(text)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2716' in position 9: ordinal not in range(128)

**Comment by dfirsec** [comment]
It appears that ThreatCrowd has removed their threat feed service.  You can use the "-r" option to remove that particular threat feed, or manually edit the feeds.json file and delete the entry.  I haven't tested on Python 3.6 so some errors may be related to that version.

**Comment by dfirsec** [comment]
Apologies, but I've decided to archive this repository in order to work on other types of projects.
